### ISSUE TITLE
Setup with regex verification causes error

### ISSUE THREAD

**Issue by joshunrau** [DouglasNeuroInformatics/DataBank#89]
```
@databank/api:dev: [13:22:16.405] ERROR (67621): request errored
@databank/api:dev:     req: "POST /v1/setup"
@databank/api:dev:     res: 500
@databank/api:dev:     responseTime: 110
@databank/api:dev:     err: {
@databank/api:dev:       "type": "PrismaClientValidationError",
@databank/api:dev:       "message": "\nInvalid `prisma.setup.create()` invocation:\n\n{\n  data: {\n    setupConfig: {\n      userVerification: {\n        kind: \"REGEX_EMAIL\",\n        regex: \".*\",\n        ~~~~~\n?       emailRegex?: String | Null\n      }\n    }\n  }\n}\n\nUnknown argument `regex`. Available options are marked with ?.",
@databank/api:dev:       "stack":
@databank/api:dev:           PrismaClientValidationError: 
@databank/api:dev:           Invalid `prisma.setup.create()` invocation:
@databank/api:dev:           
@databank/api:dev:           {
@databank/api:dev:             data: {
@databank/api:dev:               setupConfig: {
@databank/api:dev:                 userVerification: {
@databank/api:dev:                   kind: "REGEX_EMAIL",
@databank/api:dev:                   regex: ".*",
@databank/api:dev:                   ~~~~~
@databank/api:dev:           ?       emailRegex?: String | Null
@databank/api:dev:                 }
@databank/api:dev:               }
@databank/api:dev:             }
@databank/api:dev:           }
@databank/api:dev:           
@databank/api:dev:           Unknown argument `regex`. Available options are marked with ?.
@databank/api:dev:               at An (file:///Users/joshua/Developer/DNP/DataBank/api/dist/app.mjs:95626:13)
@databank/api:dev:               at _n.handleRequestError (file:///Users/joshua/Developer/DNP/DataBank/api/dist/app.mjs:96214:11)
@databank/api:dev:               at _n.handleAndLogRequestError (file:///Users/joshua/Developer/DNP/DataBank/api/dist/app.mjs:96204:16)
@databank/api:dev:               at _n.request (file:///Users/joshua/Developer/DNP/DataBank/api/dist/app.mjs:96195:16)
@databank/api:dev:               at async l (file:///Users/joshua/Developer/DNP/DataBank/api/dist/app.mjs:96649:21)
@databank/api:dev:               at async SetupService2.initApp (file:///Users/joshua/Developer/DNP/DataBank/api/dist/app.mjs:143783:5)
@databank/api:dev:       "name": "PrismaClientValidationError",
@databank/api:dev:       "clientVersion": "5.17.0"
@databank/api:dev:     }
```

**Comment by joshunrau** [comment]
Also, I would add a try catch block at the end of the setup to remove the db if there is an internal server error
