### ISSUE TITLE
Dataset with primary key that does not exist causes internal server error

### ISSUE THREAD

**Issue by joshunrau** [DouglasNeuroInformatics/DataBank#92]
```
@databank/api:dev: [Nest] 68768  - 08/29/2024, 1:33:57 PM   ERROR [ExceptionsHandler] not found: 
@databank/api:dev: Error: not found: 
@databank/api:dev:     at Proxy.getColumn (/Users/joshua/Developer/DNP/DataBank/node_modules/.pnpm/nodejs-polars@0.14.0/node_modules/nodejs-polars/bin/dataframe.js:210:46)
@databank/api:dev:     at TabularDataService2.primaryKeyCheck (file:///Users/joshua/Developer/DNP/DataBank/api/dist/app.mjs:142363:22)
@databank/api:dev:     at TabularDataService2.create (file:///Users/joshua/Developer/DNP/DataBank/api/dist/app.mjs:141992:15)
@databank/api:dev:     at DatasetsService2.createDataset (file:///Users/joshua/Developer/DNP/DataBank/api/dist/app.mjs:142946:37)
@databank/api:dev: [13:33:57.392] ERROR (68768): request errored
@databank/api:dev:     req: "POST /v1/datasets/create"
@databank/api:dev:     res: 500
@databank/api:dev:     responseTime: 33
@databank/api:dev:     err: {
@databank/api:dev:       "type": "Error",
@databank/api:dev:       "message": "not found: ",
@databank/api:dev:       "stack":
@databank/api:dev:           Error: not found: 
@databank/api:dev:               at Proxy.getColumn (/Users/joshua/Developer/DNP/DataBank/node_modules/.pnpm/nodejs-polars@0.14.0/node_modules/nodejs-polars/bin/dataframe.js:210:46)
@databank/api:dev:               at TabularDataService2.primaryKeyCheck (file:///Users/joshua/Developer/DNP/DataBank/api/dist/app.mjs:142363:22)
@databank/api:dev:               at TabularDataService2.create (file:///Users/joshua/Developer/DNP/DataBank/api/dist/app.mjs:141992:15)
@databank/api:dev:               at DatasetsService2.createDataset (file:///Users/joshua/Developer/DNP/DataBank/api/dist/app.mjs:142946:37)
@databank/api:dev:       "code": "GenericFailure"
@databank/api:dev:     }
```

**Comment by Flyinchicken** [comment]
handle internal server error by throwing a 400-level error; roll back by deleting the invalid dataset
