### ISSUE TITLE
Attempting to change pedal width to float, then to string causes 500 error

### ISSUE THREAD

**Issue by joshunrau** [DouglasNeuroInformatics/DataBank#96]
First, convert the pedal width to float. Then everything is 0. Then convert to string and this error occurs:

```
@databank/api:dev: [Nest] 73997  - 08/29/2024, 2:15:06 PM   ERROR [ExceptionsHandler] All elements of the array need to be Prisma Client promises. Hint: Please make sure you are not awaiting the Prisma client calls you intended to pass in the $transaction function.
@databank/api:dev: Error: All elements of the array need to be Prisma Client promises. Hint: Please make sure you are not awaiting the Prisma client calls you intended to pass in the $transaction function.
@databank/api:dev:     at file:///Users/joshua/Developer/DNP/DataBank/api/dist/app.mjs:96613:21
@databank/api:dev:     at Array.map (<anonymous>)
@databank/api:dev:     at Proxy._transactionWithArray (file:///Users/joshua/Developer/DNP/DataBank/api/dist/app.mjs:96611:56)
@databank/api:dev:     at o (file:///Users/joshua/Developer/DNP/DataBank/api/dist/app.mjs:96637:159)
@databank/api:dev:     at Object.runInChildSpan (file:///Users/joshua/Developer/DNP/DataBank/api/dist/app.mjs:95958:14)
@databank/api:dev:     at Proxy.$transaction (file:///Users/joshua/Developer/DNP/DataBank/api/dist/app.mjs:96639:38)
@databank/api:dev:     at ColumnsService2.mutateColumnType (file:///Users/joshua/Developer/DNP/DataBank/api/dist/app.mjs:141622:30)
@databank/api:dev: [14:15:06.446] ERROR (73997): request errored
@databank/api:dev:     req: "PATCH /v1/columns/type/66d0b9f3e6680f1171c84691"
@databank/api:dev:     res: 500
@databank/api:dev:     responseTime: 9
@databank/api:dev:     err: {
@databank/api:dev:       "type": "Error",
@databank/api:dev:       "message": "All elements of the array need to be Prisma Client promises. Hint: Please make sure you are not awaiting the Prisma client calls you intended to pass in the $transaction function.",
@databank/api:dev:       "stack":
@databank/api:dev:           Error: All elements of the array need to be Prisma Client promises. Hint: Please make sure you are not awaiting the Prisma client calls you intended to pass in the $transaction function.
@databank/api:dev:               at file:///Users/joshua/Developer/DNP/DataBank/api/dist/app.mjs:96613:21
@databank/api:dev:               at Array.map (<anonymous>)
@databank/api:dev:               at Proxy._transactionWithArray (file:///Users/joshua/Developer/DNP/DataBank/api/dist/app.mjs:96611:56)
@databank/api:dev:               at o (file:///Users/joshua/Developer/DNP/DataBank/api/dist/app.mjs:96637:159)
@databank/api:dev:               at Object.runInChildSpan (file:///Users/joshua/Developer/DNP/DataBank/api/dist/app.mjs:95958:14)
@databank/api:dev:               at Proxy.$transaction (file:///Users/joshua/Developer/DNP/DataBank/api/dist/app.mjs:96639:38)
@databank/api:dev:               at ColumnsService2.mutateColumnType (file:///Users/joshua/Developer/DNP/DataBank/api/dist/app.mjs:141622:30)
@databank/api:dev:     }
```

**Comment by joshunrau** [comment]
Maybe caused by typo (String instead of STRING)
